lesson 1;;
1+2;;
"Mary";;
'a';;
[42;1;55];;
[|"john";"doe"|];;
List.rev[1;2;3];;
List.hd[1;2;3];;
Array.append[|1;2|][|3;4;5|];;
Array.get[|42;51;32|]2;;
String.make 10 'x';;
"Mary" ^ " and" ^ " John";;
String.length "sdfghjksdfghjyuio";;
String.lowercase "MARY";;
String.concat "/" [""; "usr"; "local"; "bin"];;
int_of_string "546";;
(43, "John", true);;
fst(42, "john");;
snd(42, "john");;